# Building Pomodoro GUI using Tkinter
from tkinter import *
window=Tk()
window.minsize(width=600,height=400)
window.title("Pomodoro")
window.config(padx=100,pady=50,bg="#f7f5dd")
window.grid_columnconfigure(0,weight=1)
window.configure(bg="#f7f5dd")
tomato=Canvas(width=200,height=224,bg="#f7f5dd",highlightthickness=0)
text=Label(text="TIMER",font=("Arial",24,"bold"),bg="#f7f5dd",fg="#9bdeac",highlightthickness=0)
start=Button(text="Start",width=10,highlightthickness=0,)
reset=Button(text="Reset",width=10,highlightthickness=0)
text.grid(row=0,column=0,pady=(20,10),columnspan=2)
tomato.grid(column=0,row=1,columnspan=2)
start.grid(row=3,column=0,padx=20,pady=10)
reset.grid(row=3,column=1,padx=20,pady=10)
photo=PhotoImage(file="tomato.png")
tomato.create_image(100,112,image=photo)
window.mainloop()
